
#cmakedefine HAVE_FLOAT_H ${HAVE_FLOAT_H}
#cmakedefine HAVE_INTTYPES_H ${HAVE_INTTYPES_H}
#cmakedefine HAVE_LIMITS_H ${HAVE_LIMITS_H}
#cmakedefine HAVE_LOCALE_H ${HAVE_LOCALE_H}
#cmakedefine HAVE_STDDEF_H ${HAVE_STDDEF_H}
#cmakedefine HAVE_STDINT_H ${HAVE_STDINT_H}
#cmakedefine HAVE_STDLIB_H ${HAVE_STDLIB_H}
#cmakedefine HAVE_STRING_H ${HAVE_STRING_H}
#cmakedefine HAVE_UNISTD_H ${HAVE_UNISTD_H}
#cmakedefine HAVE_WCHAR_H ${HAVE_WCHAR_H}
#cmakedefine HAVE_WCTYPE_H ${HAVE_WCTYPE_H}
#cmakedefine HAVE_FLOOR ${HAVE_FLOOR}
#cmakedefine HAVE_ISASCII ${HAVE_ISASCII}
#cmakedefine HAVE_LOCALECONV ${HAVE_LOCALECONV}
#cmakedefine HAVE_MBLEN ${HAVE_MBLEN}
#cmakedefine HAVE_MEMMOVE ${HAVE_MEMMOVE}
#cmakedefine HAVE_MEMSET ${HAVE_MEMSET}
#cmakedefine HAVE_MODF ${HAVE_MODF}
#cmakedefine HAVE_POW ${HAVE_POW}
#cmakedefine HAVE_SQRT ${HAVE_SQRT}
#cmakedefine HAVE_STRCASECMP ${HAVE_STRCASECMP}
#cmakedefine HAVE_STRCHR ${HAVE_STRCHR}
#cmakedefine HAVE_STRERROR ${HAVE_STRERROR}
#cmakedefine HAVE_STRNCASECMP ${HAVE_STRNCASECMP}
#cmakedefine HAVE_STRRCHR ${HAVE_STRRCHR}
#cmakedefine HAVE_STRSTR ${HAVE_STRSTR}
#cmakedefine HAVE_STRTOL ${HAVE_STRTOL}
#cmakedefine HAVE_STRTOUL ${HAVE_STRTOUL}
#cmakedefine HAVE_PTRDIFF_T ${HAVE_PTRDIFF_T}
#cmakedefine HAVE_SIZE_T ${HAVE_SIZE_T}
#cmakedefine size_t ${size_t}
#cmakedefine TM_IN_SYS_TIME ${TM_IN_SYS_TIME}
#cmakedefine HAVE_STRCOLL ${HAVE_STRCOLL}
#cmakedefine HAVE_STRFTIME ${HAVE_STRFTIME}
#cmakedefine HAVE_VPRINTF ${HAVE_VPRINTF}
